AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*

Metrics/LineLength:
  Max: 145

Metrics/BlockLength:
  Max: 42

Style/Documentation:
  Enabled: false

AssignmentInCondition:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MethodLength:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - spec/translateable_attributes_spec.rb
